# Site settings
title: InfoSec Sandbox
description: A place to play with things I'm learning
keywords: infosec, security, Fun
author: InfoSec
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
