title:              InfoSec Sandbox
email:              sandboxinfosec@gmail.com
description:        Sandbox for all things InfoSec
author:             InfoSec Sandbox
baseurl:            "/infosecsandbox.github.io"
url:                "https://infosecsandbox.github.io"

# Social Profiles
twitter_username:   infosecsandbox
github_username:    InfoSecSandbox
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
